stages:
  - build
  - test

build:
  stage: build
  script:
    - cargo build
test:
  stage: test
  script:
    - cargo +nightly fmt -- --check
    - cargo test
  dependencies:
    - build
  variables:
    GIT_STRATEGY: none
