stages:
  - build
  - test

build:
  stage: build
  script:
    - cargo build
test:
  stage: test
  script:
    - cargo +nightly fmt --package bespin -- --check
    - RUST_TEST_THREADS=1 cargo test
  dependencies:
    - build
  variables:
    GIT_STRATEGY: none
