stages:
  - build
  - test
  - bench

build:
  stage: build
  script:
    - sudo apt install libhwloc-dev libfreetype6 libfreetype6-dev gnuplot --yes
    - cargo build
test:
  stage: test
  script:
    - cargo +nightly fmt -- --check
    - cargo test
  dependencies:
    - build
  variables:
    GIT_STRATEGY: none

bench:
  stage: bench
  script:
    - cargo bench
  dependencies:
    - test
  variables:
    GIT_STRATEGY: none
