[package]
name = "node-replication"
version = "0.1.0"
authors = ["Chinmay Kulkarni"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = { git = "https://github.com/gz/criterion.rs", branch = "iter-custom" }

[[bench]]
name = "criterion_bench"
harness = false