[package]
name = "node-replication"
version = "0.1.0"
authors = ["Chinmay Kulkarni"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-utils = "0.6"

# Debug symbols on the release build so that we can debug performance quirks
[profile.release]
debug = true

[dev-dependencies]
chrono = "0.4"
core_affinity = { git = "https://github.com/nau/core_affinity_rs", branch = "patch-1" }
clap = { version = "2", features = ["yaml"] }
criterion = { git = "https://github.com/gz/criterion.rs", branch = "iter-custom" }
csv = "0.*"
nom = "^1.2.3"
plotters = "^0.2.2"
rand = "0.7"
rustc-serialize = "0.3"

[[bench]]
name = "criterion_bench"
harness = false
