name: Deploy Benchmark

on: [push]

jobs:
  build:
    name: Build and test on ${{ matrix.os }} with rustc ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]

    steps:
    - name: Install dependencies
      run: sudo apt-get install -y libhwloc-dev libfreetype6 libfreetype6-dev gnuplot numactl
    - name: Set up a Rust toolchain
      uses: hecrj/setup-rust-action@v1.0.2
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v1
    - name: Try to run benchmarks
      run: cargo bench
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.GH_PAGES }}
        BRANCH: gh-pages
        FOLDER: target/criterion/report
        BUILD_SCRIPT: npm install && npm run-script build
