name: Rust

on: [push]

jobs:
  build:
    name: Build and test on ${{ matrix.os }} with rustc {{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]

    steps:
    - name: Set up a Rust toolchain
      uses: hecrj/setup-rust-action@v1.0.2
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
