name: Rust

on: [push]

jobs:
  build:
    name: Build and test on ${{ matrix.os }} with rustc ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]

    steps:
    - name: Install dependencies
      run: sudo apt-get install libhwloc-dev libfreetype6 libfreetype6-dev gnuplot
    - name: Set up a Rust toolchain
      uses: hecrj/setup-rust-action@v1.0.2
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Try stack example
      run: RUST_LOG='debug' cargo run --release --example stack -- -t1,2 --nop 100000 -l 1 -m sequential
